language: python
python:
  - 2.7
  - 3.6
services:
  - postgresql
env:
  -DJANGO=1.10 DB=postgresql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - python manage.py test
